package br.com.contmatic.model.v1.endereco;

public enum PaisType {
	
	AFEGANISTAO("Afeganistão"),
	AFRICA_DO_SUL("África do Sul"),
	AKROTIRI("Akrotiri"),
	ALBANIA("Albânia"),
	ALEMANHA("Alemanha"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	ANGUILA("Anguila"),
	ANTARCTIDA("Antárctida"),
	ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
	ARABIA_SAUDITA("Arábia Saudita"),
	ARCTIC_OCEAN("Arctic Ocean"),
	ARGELIA("Argélia"),
	ARGENTINA("Argentina"),
	ARMENIA("Arménia"),
	ARUBA("Aruba"),
	ASHMORE_AND_CARTIER_ISLANDS("Ashmore and Cartier Islands"),
	ATLANTIC_OCEAN("Atlantic Ocean"),
	AUSTRALIA("Austrália"),
	AUSTRIA("Áustria"),
	AZERBAIJAO("Azerbaijão"),
	BAAMAS("Baamas"),
	BANGLADECHE("Bangladeche"),
	BARBADOS("Barbados"),
	BAREM("Barém"),
	BELGICA("Bélgica"),
	BELIZE("Belize"),
	BENIM("Benim"),
	BERMUDAS("Bermudas"),
	BIELORRUSSIA("Bielorrússia"),
	BIRMANIA("Birmânia"),
	BOLIVIA("Bolívia"),
	BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
	BOTSUANA("Botsuana"),
	BRASIL("Brasil"),
	BRUNEI("Brunei"),
	BULGARIA("Bulgária"),
	BURQUINA_FASO("Burquina Faso"),
	BURUNDI("Burúndi"),
	BUTAO("Butão"),
	CABO_VERDE("Cabo Verde"),
	CAMAROES("Camarões"),
	CAMBOJA("Camboja"),
	CANADA("Canadá"),
	CATAR("Catar"),
	CAZAQUISTAO("Cazaquistão"),
	CHADE("Chade"),
	CHILE("Chile"),
	CHINA("China"),
	CHIPRE("Chipre"),
	CLIPPERTON_ISLAND("Clipperton Island"),
	COLOMBIA("Colômbia"),
	COMORES("Comores"),
	CONGO_BRAZZAVILLE("Congo-Brazzaville"),
	CONGO_KINSHASA("Congo-Kinshasa"),
	CORAL_SEA_ISLANDS("Coral Sea Islands"),
	COREIA_DO_NORTE("Coreia do Norte"),
	COREIA_DO_SUL("Coreia do Sul"),
	COSTA_DO_MARFIM("Costa do Marfim"),
	COSTA_RICA("Costa Rica"),
	CROACIA("Croácia"),
	CUBA("Cuba"),
	CURACAO("Curacao"),
	DHEKELIA("Dhekelia"),
	DINAMARCA("Dinamarca"),
	DOMINICA("Domínica"),
	EGIPTO("Egipto"),
	EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
	EQUADOR("Equador"),
	ERITREIA("Eritreia"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovénia"),
	ESPANHA("Espanha"),
	ESTADOS_UNIDOS("Estados Unidos"),
	ESTONIA("Estónia"),
	ETIOPIA("Etiópia"),
	FAROE("Faroé"),
	FIJI("Fiji"),
	FILIPINAS("Filipinas"),
	FINLANDIA("Finlândia"),
	FRANCA("França"),
	GABAO("Gabão"),
	GAMBIA("Gâmbia"),
	GANA("Gana"),
	GAZA_STRIP("Gaza Strip"),
	GEORGIA("Geórgia"),
	GEORGIA_DO_SUL_E_SANDWICH_DO_SUL("Geórgia do Sul e Sandwich do Sul"),
	GIBRALTAR("Gibraltar"),
	GRANADA("Granada"),
	GRECIA("Grécia"),
	GRONELANDIA("Gronelândia"),
	GUAME("Guame"),
	GUATEMALA("Guatemala"),
	GUERNSEY("Guernsey"),
	GUIANA("Guiana"),
	GUINE("Guiné"),
	GUINE_EQUATORIAL("Guiné Equatorial"),
	GUINE_BISSAU("Guiné-Bissau"),
	HAITI("Haiti"),
	HONDURAS("Honduras"),
	HONG_KONG("Hong Kong"),
	HUNGRIA("Hungria"),
	IEMEN("Iémen"),
	ILHA_BOUVET("Ilha Bouvet"),
	ILHA_DO_NATAL("Ilha do Natal"),
	ILHA_NORFOLK("Ilha Norfolk"),
	ILHAS_CAIMAO("Ilhas Caimão"),
	ILHAS_COOK("Ilhas Cook"),
	ILHAS_DOS_COCOS("Ilhas dos Cocos"),
	ILHAS_FALKLAND("Ilhas Falkland"),
	ILHAS_HEARD_E_MCDONALD("Ilhas Heard e McDonald"),
	ILHAS_MARSHALL("Ilhas Marshall"),
	ILHAS_SALOMAO("Ilhas Salomão"),
	ILHAS_TURCAS_E_CAICOS("Ilhas Turcas e Caicos"),
	ILHAS_VIRGENS_AMERICANAS("Ilhas Virgens Americanas"),
	ILHAS_VIRGENS_BRITANICAS("Ilhas Virgens Britânicas"),
	INDIA("Índia"),
	INDIAN_OCEAN("Indian Ocean"),
	INDONESIA("Indonésia"),
	IRA("Ira"),
	IRAQUE("Iraque"),
	IRLANDA("Irlanda"),
	ISLANDIA("Islândia"),
	ISRAEL("Israel"),
	ITALIA("Itália"),
	JAMAICA("Jamaica"),
	JAN_MAYEN("Jan Mayen"),
	JAPAO("Japão"),
	JERSEY("Jersey"),
	DJIBUTI("Djibuti"),
	JORDANIA("Jordânia"),
	KOSOVO("Kosovo"),
	KUWAIT("Kuwait"),
	LAOS("Laos"),
	LESOTO("Lesoto"),
	LETONIA("Letónia"),
	LIBANO("Líbano"),
	LIBERIA("Libéria"),
	LIBIA("Líbia"),
	LISTENSTAINE("Listenstaine"),
	LITUANIA("Lituânia"),
	LUXEMBURGO("Luxemburgo"),
	MACAU("Macau"),
	MACEDONIA("Macedónia"),
	MADAGASCAR("Madagáscar"),
	MALASIA("Malásia"),
	MALAWI("Malawi"),
	MALDIVAS("Maldivas"),
	MALI("Mali"),
	MALTA("Malta"),
	ISLE_OF_MAN("Man, Isle of"),
	MARIANAS_DO_NORTE("Marianas do Norte"),
	MARROCOS("Marrocos"),
	MAURICIO("Maurício"),
	MAURITANIA("Mauritânia"),
	MEXICO("México"),
	MICRONESIA("Micronésia"),
	MOCAMBIQUE("Moçambique"),
	MOLDAVIA("Moldávia"),
	MONACO("Mónaco"),
	MONGOLIA("Mongólia"),
	MONSERRATE("Monserrate"),
	MONTENEGRO("Montenegro"),
	MUNDO("Mundo"),
	NAMIBIA("Namíbia"),
	NAURU("Nauru"),
	NAVASSA_ISLAND("Navassa Island"),
	NEPAL("Nepal"),
	NICARAGUA("Nicarágua"),
	NIGER("Níger"),
	NIGERIA("Nigéria"),
	NIUE("Niue"),
	NORUEGA("Noruega"),
	NOVA_CALEDONIA("Nova Caledónia"),
	NOVA_ZELANDIA("Nova Zelândia"),
	OMA("Omã"),
	PACIFIC_OCEAN("Pacific Ocean"),
	PAISES_BAIXOS("Países Baixos, Holanda"),
	PALAU("Palau"),
	PANAMA("Panamá"),
	PAPUA_NOVA_GUINE("Papua-Nova Guiné"),
	PAQUISTAO("Paquistão"),
	PARACEL_ISLANDS("Paracel Islands"),
	PARAGUAI("Paraguai"),
	PERU("Peru"),
	PITCAIRN("Pitcairn"),
	POLINESIA_FRANCESA("Polinésia Francesa"),
	POLONIA("Polónia"),
	PORTO_RICO("Porto Rico"),
	PORTUGAL("Portugal"),
	QUENIA("Quénia"),
	QUIRGUIZISTAO("República Quirguiz"),
	QUIRIBATI("Quiribáti"),
	REINO_UNIDO("Reino Unido"),
	REPUBLICA_CENTRO_AFRICANA("República Centro-Africana"),
	REPUBLICA_DOMINICANA("República Dominicana"),
	ROMENIA("Roménia"),
	RUANDA("Ruanda"),
	RUSSIA("Rússia"),
	EL_SALVADOR("El Salvador"),
	SAMOA("Samoa"),
	SAMOA_AMERICANA("Samoa Americana"),
	SANTA_HELENA("Santa Helena"),
	SANTA_LUCIA("Santa Lúcia"),
	SAO_BARTOLOMEU("São Bartolomeu"),
	SAO_CRISTOVAO_E_NEVES("São Cristóvão e Neves"),
	SAO_MARINHO("São Marinho"),
	SAO_MARTINHO("São Martinho"),
	SAO_PEDRO_E_MIQUELON("São Pedro e Miquelon"),
	SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
	SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
	SAARA_OCIDENTAL("Saara Ocidental"),
	SEICHELES("Seicheles"),
	SENEGAL("Senegal"),
	SERRA_LEOA("Serra Leoa"),
	SERVIA("Sérvia"),
	SINGAPURA("Singapura"),
	SINT_MAARTEN("Sint Maarten"),
	SIRIA("Síria"),
	SOMALIA("Somália"),
	SOUTHERN_OCEAN("Southern Ocean"),
	SPRATLY_ISLANDS("Spratly Islands"),
	SRI_LANCA("Sri Lanca"),
	SUAZILANDIA("Suazilândia"),
	SUDAO("Sudão"),
	SUDSO_DO_SUL("Sudão do Sul"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	SURINAME("Suriname"),
	SVALBARD_E_JAN_MAYEN("Svalbard e Jan Mayen"),
	TAILANDIA("Tailândia"),
	TAIWAN("Taiwan"),
	TAJIQUISTAO("Tajiquistão"),
	TANZANIA("Tanzânia"),
	TERRITORIO_BRITANICO_DO_OCEANO_INDICO("Território Britânico do Oceano Índico"),
	TERRITORIOS_AUSTRAIS_FRANCESES("Territórios Austrais Franceses"),
	TIMOR_LESTE("Timor Leste"),
	TOGO("Togo"),
	TOKELAU("Tokelau"),
	TONGA("Tonga"),
	TRINDADE_E_TOBAGO("Trindade e Tobago"),
	TUNISIA("Tunísia"),
	TURQUEMENISTAO("Turquemenistão"),
	TURQUIA("Turquia"),
	TUVALU("Tuvalu"),
	UCRANIA("Ucrânia"),
	UGANDA("Uganda"),
	UNIAO_EUROPEIA("União Europeia"),
	URUGUAI("Uruguai"),
	USBEQUISTAO("República do Usbequistão"),
	VANUATU("Vanuatu"),
	VATICANO("Vaticano"),
	VENEZUELA("Venezuela"),
	VIETNA("Vietna"),
	WAKE_ISLAND("Wake Island"),
	WALLIS_E_FUTUNA("Wallis e Futuna"),
	WEST_BANK("West Bank"),
	ZAMBIA("Zâmbia"),
	ZIMBABUE("Zimbabué"), 
	EGITO("Egito"), 
	BAHAMAS("Bahamas"), 
	ILHA_DE_ASCENSAO("Ilha de Ascensão"), 
	REUNIAO("Reunião"),
	MAYOTTE("Departamento de Mayotte"), 
	GROELANDIA("Groelândia"),
	REPUBLICA_TCHECA("República Tcheca"), 
	GRENADA("Grenade"), 
	GUADALUPE("Guadalupe"),
	GUIANA_FRANCESA("Guiana Francesa"), 
	MARTINICA("Martinica"), 
	ESTADO_DE_PALESTINA("Estado da Palestina"),
	NAO_PRESENTE("País não presente.");

	private String nome;

	private PaisType(String nome) {
		this.nome = nome;
	}

	public String getNome() {
		return nome;
	}

}
